name: Caliper test
version: "2.0.0"

caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: true

channels:
  - channelName: mychannel
    contracts:
      - id: fabcar

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: "appUser"
          clientPrivateKey:
            path: "../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/37cc4d6e223632529ecfa71146f985de87b27c0d13d27067b20269df258f75ab_sk"
          clientSignedCert:
            path: "../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem"
    connectionProfile:
      path: "../test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml"
      discover: true
